sudo: false

language: ruby

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.8"
  - "2.2.4"
  - "2.3.0"
  - "jruby-19mode"
  - "rbx"

gemfile:
  - "gemfiles/capistrano2.gemfile"
  - "gemfiles/capistrano3.gemfile"
  - "gemfiles/no_dependencies.gemfile"
  - "gemfiles/padrino.gemfile"
  - "gemfiles/rails-3.2.gemfile"
  - "gemfiles/rails-4.0.gemfile"
  - "gemfiles/rails-4.1.gemfile"
  - "gemfiles/rails-4.2.gemfile"
  - "gemfiles/rails-5.0.gemfile"
  - "gemfiles/sequel.gemfile"
  - "gemfiles/sinatra.gemfile"

matrix:
  allow_failures:
    - rvm: "rbx"
    - rvm: "jruby-19mode"

env:
  global: "RAILS_ENV=test"

script: "bundle exec rspec"
